#!/usr/bin/env python3
"""Generate Gmsh geometry from nozzle point coordinates."""

from __future__ import annotations

import argparse
import csv
import math
import statistics
from pathlib import Path


def parse_points(
    path: Path, deduplicate_consecutive: bool = True, tol: float = 1e-12
) -> tuple[list[tuple[float, float]], int]:
    points: list[tuple[float, float]] = []
    dropped_duplicates = 0

    with path.open(newline="") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) < 3:
                continue
            try:
                x = float(row[1].strip())
                y = float(row[2].strip())
            except ValueError:
                continue
            if not (math.isfinite(x) and math.isfinite(y)):
                continue
            if deduplicate_consecutive and points:
                px, py = points[-1]
                if abs(x - px) <= tol and abs(y - py) <= tol:
                    dropped_duplicates += 1
                    continue
            points.append((x, y))

    if len(points) < 2:
        raise ValueError(f"Need at least 2 valid points in {path}")

    return points, dropped_duplicates


def build_wall_curves(
    points: list[tuple[float, float]],
    line_gap_factor: float,
    force_line_ranges: set[tuple[int, int]] | None = None,
    force_line_edges: set[int] | None = None,
) -> tuple[list[tuple[str, int, list[int]]], list[int], float, float, int]:
    force_line_ranges = force_line_ranges or set()
    force_line_edges = force_line_edges or set()
    gaps = [
        math.hypot(points[i + 1][0] - points[i][0], points[i + 1][1] - points[i][1])
        for i in range(len(points) - 1)
    ]
    positive_gaps = [g for g in gaps if g > 0.0]
    typical_gap = statistics.median(positive_gaps) if positive_gaps else 0.0
    threshold = (
        typical_gap * line_gap_factor
        if line_gap_factor > 0.0 and typical_gap > 0.0
        else math.inf
    )

    break_after = [i + 1 for i, g in enumerate(gaps) if g > threshold]
    break_after.extend(sorted(force_line_edges))
    break_after = sorted(set(b for b in break_after if 1 <= b < len(points)))

    curves: list[tuple[str, int, list[int]]] = []
    wall_curve_ids: list[int] = []
    next_curve_id = 1
    start = 1

    def append_chain_curve(a: int, b: int) -> None:
        nonlocal next_curve_id
        npts = b - a + 1
        if npts < 2:
            return
        if npts == 2 or (a, b) in force_line_ranges:
            curves.append(("Line", next_curve_id, [a, b]))
        else:
            curves.append(("Spline", next_curve_id, list(range(a, b + 1))))
        wall_curve_ids.append(next_curve_id)
        next_curve_id += 1

    for i in break_after:
        append_chain_curve(start, i)
        curves.append(("Line", next_curve_id, [i, i + 1]))
        wall_curve_ids.append(next_curve_id)
        next_curve_id += 1
        start = i + 1

    append_chain_curve(start, len(points))

    return curves, wall_curve_ids, typical_gap, threshold, len(break_after)


def write_wall_geo(
    points: list[tuple[float, float]],
    out_path: Path,
    lc_wall: float,
    wall_curves: list[tuple[str, int, list[int]]],
    wall_curve_ids: list[int],
) -> None:
    with out_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by generate_nozzle_gmsh.py\n")
        f.write("SetFactory(\"OpenCASCADE\");\n\n")

        for i, (x, y) in enumerate(points, start=1):
            f.write(f"Point({i}) = {{{x:.12g}, {y:.12g}, 0, {lc_wall:.12g}}};\n")

        f.write("\n")
        for kind, cid, ids in wall_curves:
            if kind == "Spline":
                f.write(f"Spline({cid}) = {{{', '.join(str(i) for i in ids)}}};\n")
            else:
                f.write(f"Line({cid}) = {{{ids[0]}, {ids[1]}}};\n")
        f.write("\n")
        f.write(
            'Physical Curve("SOLID_WALL") = {'
            + ", ".join(str(i) for i in wall_curve_ids)
            + "};\n"
        )


def write_domain_geo(
    points: list[tuple[float, float]],
    out_path: Path,
    lc_wall: float,
    lc_far: float,
    top_pad: float,
    wall_curves: list[tuple[str, int, list[int]]],
    wall_curve_ids: list[int],
) -> None:
    x0, y0 = points[0]
    x1, _ = points[-1]
    ymax = max(y for _, y in points)
    y_top = ymax + top_pad

    tl_point_id = len(points) + 1
    tr_point_id = len(points) + 2
    next_curve_id = max(wall_curve_ids) + 1

    with out_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by generate_nozzle_gmsh.py\n")
        f.write("SetFactory(\"OpenCASCADE\");\n\n")

        for i, (x, y) in enumerate(points, start=1):
            f.write(f"Point({i}) = {{{x:.12g}, {y:.12g}, 0, {lc_wall:.12g}}};\n")

        f.write(
            f"\nPoint({tl_point_id}) = {{{x0:.12g}, {y_top:.12g}, 0, {lc_far:.12g}}};\n"
        )
        f.write(
            f"Point({tr_point_id}) = {{{x1:.12g}, {y_top:.12g}, 0, {lc_far:.12g}}};\n\n"
        )

        for kind, cid, ids in wall_curves:
            if kind == "Spline":
                f.write(f"Spline({cid}) = {{{', '.join(str(i) for i in ids)}}};\n")
            else:
                f.write(f"Line({cid}) = {{{ids[0]}, {ids[1]}}};\n")

        inlet_id = next_curve_id
        farfield_id = next_curve_id + 1
        outlet_id = next_curve_id + 2

        f.write(f"Line({inlet_id}) = {{1, {tl_point_id}}};\n")
        f.write(f"Line({farfield_id}) = {{{tl_point_id}, {tr_point_id}}};\n")
        f.write(f"Line({outlet_id}) = {{{tr_point_id}, {len(points)}}};\n\n")

        wall_back = ", ".join(f"-{cid}" for cid in reversed(wall_curve_ids))
        f.write(
            f"Curve Loop(1) = {{{inlet_id}, {farfield_id}, {outlet_id}, {wall_back}}};\n"
        )
        f.write("Plane Surface(1) = {1};\n\n")
        f.write(
            'Physical Curve("SOLID_WALL") = {'
            + ", ".join(str(i) for i in wall_curve_ids)
            + "};\n"
        )
        f.write(f'Physical Curve("INLET") = {{{inlet_id}}};\n')
        f.write(f'Physical Curve("FARFIELD") = {{{farfield_id}}};\n')
        f.write(f'Physical Curve("OUTLET") = {{{outlet_id}}};\n')
        f.write('Physical Surface("FLUID") = {1};\n')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", nargs="?", default="nozzle_coordinates.txt", help="Input CSV-like coordinate file")
    parser.add_argument("--wall-geo", default="nozzle_wall.geo", help="Output .geo for wall spline only")
    parser.add_argument("--domain-geo", default="nozzle_cfd_domain.geo", help="Output .geo for 2D CFD domain")
    parser.add_argument(
        "--keep-duplicates",
        action="store_true",
        help="Keep exactly repeated consecutive points (can break OpenCASCADE spline creation)",
    )
    parser.add_argument(
        "--line-gap-factor",
        type=float,
        default=8.0,
        help=(
            "Convert unusually large point-to-point gaps into Line entities when "
            "distance > median_gap * factor. Set <=0 to disable."
        ),
    )
    parser.add_argument(
        "--force-line-range",
        action="append",
        default=[],
        help=(
            "Force a contiguous point-id span to use Line(start,end) instead of "
            "Spline(start..end). Format: START-END (e.g. 33-426). Can be repeated."
        ),
    )
    parser.add_argument(
        "--force-line-edge",
        action="append",
        default=[],
        help=(
            "Force only one edge to Line(start,end), keeping spline before/after. "
            "Format: START-END where END = START+1 (e.g. 33-34). Can be repeated."
        ),
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    wall_geo = Path(args.wall_geo)
    domain_geo = Path(args.domain_geo)

    points, dropped_duplicates = parse_points(
        input_path, deduplicate_consecutive=not args.keep_duplicates
    )

    xmin = min(x for x, _ in points)
    xmax = max(x for x, _ in points)
    ymin = min(y for _, y in points)
    ymax = max(y for _, y in points)
    lx = xmax - xmin
    ly = ymax - ymin

    lc_wall = max(lx / 250.0, 1e-4)
    lc_far = 5.0 * lc_wall
    top_pad = max(0.5 * ly, 0.08 * lx)

    force_line_ranges: set[tuple[int, int]] = set()
    for spec in args.force_line_range:
        try:
            a_str, b_str = spec.split("-", maxsplit=1)
            a = int(a_str)
            b = int(b_str)
        except ValueError as e:
            raise ValueError(f"Invalid --force-line-range '{spec}', expected START-END") from e
        if a < 1 or b < 1 or b < a:
            raise ValueError(f"Invalid --force-line-range '{spec}', must satisfy 1 <= START <= END")
        force_line_ranges.add((a, b))

    force_line_edges: set[int] = set()
    for spec in args.force_line_edge:
        try:
            a_str, b_str = spec.split("-", maxsplit=1)
            a = int(a_str)
            b = int(b_str)
        except ValueError as e:
            raise ValueError(f"Invalid --force-line-edge '{spec}', expected START-END") from e
        if abs(a - b) != 1:
            raise ValueError(
                f"Invalid --force-line-edge '{spec}', points must be consecutive (e.g. 33-34)"
            )
        k = min(a, b)
        if k < 1:
            raise ValueError(f"Invalid --force-line-edge '{spec}', point ids must be >= 1")
        force_line_edges.add(k)

    wall_curves, wall_curve_ids, typical_gap, threshold, n_line_breaks = build_wall_curves(
        points,
        args.line_gap_factor,
        force_line_ranges=force_line_ranges,
        force_line_edges=force_line_edges,
    )

    write_wall_geo(points, wall_geo, lc_wall, wall_curves, wall_curve_ids)
    write_domain_geo(
        points, domain_geo, lc_wall, lc_far, top_pad, wall_curves, wall_curve_ids
    )

    print(f"Read {len(points)} points from {input_path}")
    print(
        "Consecutive duplicate handling: "
        + ("kept" if args.keep_duplicates else "deduplicated")
    )
    print(f"Dropped consecutive duplicates: {dropped_duplicates}")
    print(
        f"Gap rule: line when gap > median*factor = {typical_gap:.6g} * "
        f"{args.line_gap_factor:.6g} = "
        + ("disabled" if not math.isfinite(threshold) else f"{threshold:.6g}")
    )
    print(f"Large-gap spans converted to Line: {n_line_breaks}")
    if force_line_ranges:
        forced = ", ".join(f"{a}-{b}" for a, b in sorted(force_line_ranges))
        print(f"Forced Line ranges: {forced}")
    if force_line_edges:
        forced_edges = ", ".join(f"{k}-{k+1}" for k in sorted(force_line_edges))
        print(f"Forced Line edges: {forced_edges}")
    print(f"Wall curves: {len(wall_curve_ids)} total")
    print(f"Wrote {wall_geo}")
    print(f"Wrote {domain_geo}")
    print(f"lc_wall={lc_wall:.6g}, lc_far={lc_far:.6g}, top_pad={top_pad:.6g}")


if __name__ == "__main__":
    main()
